name: DevilKits
main: me.devilkits.Main
version: 1.0
description: Editado por DevilSecktor
author: DevilSecktor
commands: 
    ban:
    bcb:
    broadboss:
    paladino:
    homeminvisivel:
    hg:
    fechar:
    clear:
    kick:
    pvp:
    sethg:
    pulapula:
    youtuber:
    avatar:
    grappler:
    netherman:
    fujao:
    tag:
    stoneman:
    anchor:
    archer:
    titan:
    ghoul:
    infernor:
    chat:
    naruto:
    camel:
    fireman:
    madman:
    reaper:
    turtle:
    sumo:
    saldo:
    settextura:
    textura:
    grappler:
    boxer:
    hulk:
    mdr:
    milkman:
    chat:
    head:
    setrdm:
    rdm:
    setmdr:
    ghoul:
    titan:
    confuser:
    darkgod:
    endermage:
    lobisomem:
    fisherman:
    homempedra:
    hunter:
    weaksword:
    critical:
    launcher:
    espada:
    viking:
    specialist:
    barbarian:
    gm:
    naruto:
    berserker:
    resouper:
    fly:
    dia:
    noite:
    staffchat:
    invsee:
    tpall:
    thor:
    gambler:
    skit:
    togglepvp:
    gladiator:
    jellyfish:
    report:
    c4:
    morf:
    batman:
    wolverine:
    say:
    ip:
    timelord:
    kangaroo:
    monk:
    ninja:
    granadier:
    ryu:
    poseidon:
    frosty:
    snail:
    build:
    morrer:
    stomper:
    loja:
    coder:
    switcher:
    cc:
    urgal:
    kits:
    kits2:
    flash:
    phantom:
    sniper:
    skeleton:
    grandpa:
    ryu:
    salamander:
    warps:
    robinhood:
    viper:
    kits:
    copycat:
    fps:
    setfps:
    setmain:
    setchallenge:
    challenge:
    main:
    setknock:
    setmlg:
    mlg:
    knock:
    setspawn:
    spawn:
    resetkit:
    .: